### ISSUE TITLE
Require CI to merge

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/hotline#12]
It's possible to merge without CI being green:

<img width="692" alt="screen shot 2017-01-19 at 18 39 45" src="https://cloud.githubusercontent.com/assets/1158274/22118145/f5e60626-de76-11e6-8680-e9538a1c9719.png">

**Comment by enfluid** [comment]
Done!

**Comment by rudolf-adamkovic** [comment]
@enfluid That was **FAST**. Working! Thanks.
