### ISSUE TITLE
Rename repository to Hotline

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/hotline#27]
The original was renamed to Hotline. We had to rename the project from HotlineIO to Hotline to have properly working Xcode project — umbrella header, etc. Please, rename the repo to match the Xcode project and framework.

Next up: Update URL in BuddyBuild

**Comment by enfluid** [comment]
Renamed it to `hotline` with lower-case.  Is that what you want, or you need it to be Upper case?

**Comment by rudolf-adamkovic** [comment]
Next up, we need to fix this:

https://github.com/enfluid/hotline/pull/26#issuecomment-287458538

Please, can you configure GitHub to use `Hotline` (Release) instead of `HotlineIO` scheme for BuddyBuild?

**Comment by enfluid** [comment]
Umm... These are the only options, and this is how it's configured:

![2017-03-17_1412](https://cloud.githubusercontent.com/assets/3988018/24061155/e6933dc0-0b1b-11e7-9383-33aa911a40be.png)

**Comment by rudolf-adamkovic** [comment]
Uh, looks like BuddyBuild doesn't handle this properly.

**Comment by rudolf-adamkovic** [comment]
Re-adding the framework to BuddyBuild.

**Comment by rudolf-adamkovic** [comment]
All right, I re-added it. We need to make GitHub talk to BuddyBuild. Please, take a look:
https://dashboard.buddybuild.com/apps/58cc4b47289c8d0100ae8bc6

**Comment by enfluid** [comment]
Done.  Just updated the payload url of the the existing web hook

**Comment by rudolf-adamkovic** [comment]
The red bar is still present.

**Comment by enfluid** [comment]
Okay, deleted and re-added.  Red bar is gone now.

**Comment by rudolf-adamkovic** [comment]
Perfect, thanks!

**Comment by rudolf-adamkovic** [comment]
Look at the `REQUIRED` tag here:

<img width="689" alt="screen shot 2017-03-17 at 22 58 47" src="https://cloud.githubusercontent.com/assets/1158274/24064556/650dcd5c-0b65-11e7-8b82-d75240003947.png">

Could you please double-check that `Hotline` (and not `HotlineIO`) is required?

**Comment by enfluid** [comment]
Done!
